### ISSUE TITLE
Failed JSON-LD normalization

### ISSUE THREAD

**Issue by dalesupa22** [blockchain-certificates/cert-verifier-js#1609]
Hi guys,
In your recent version [1.57.2](https://www.npmjs.com/package/@blockcerts/blockcerts-verifier/v/1.57.2) we are getting the following error **Failed JSON-LD normalization** .
We were searching for details and we found a solution🙂. If you remove the publicKey attribute inside the verification general attribute the problem will be fixed without affecting the Blockcerts verification process.
The problem with this is that we need to remove the publicKey attribute in all the previous generated JSONs which is quite expensive😢😢😢.
Looking forward to hearing from you and find alternatives.

Maybe is because the current public key structure has the following syntax with "-" symbol I dont know.
"verification": {
      "type": [
         "MerkleProofVerification2017",
         "Extension"
      ],
      "publicKey": "ecdsa-koblitz-pubkey0x8Ad1fC3f16795Ab926BD3CHANGEDFORSECURITY"
   }

**Comment by lemoustachiste** [comment]
ok so I'm transferring this issue to this repo because it's the package.

This is indeed an issue related to jsonld safe mode, which was introduced with a recent update. 
However we can't really consider this a bug on the verifier side, as it is conforming to a safer jsonld parser. There is likely an issue with your model and I'm trying to pinpoint it.

**Comment by lemoustachiste** [comment]
The quick error fix is the format of the public key:

`ecdsa-koblitz-pubkey0x8Ad1fC3f16795Ab926BD3CHANGEDFORSECURITY`

if it is referenced as 

`ecdsa-koblitz-pubkey:0x8Ad1fC3f16795Ab926BD3CHANGEDFORSECURITY`

Then the issue does not appear. 

So I don't exactly know at this point why jsonld needs the colon, but may I ask if that's a typo, or if not, why do you drop the colon? Other public keys expect the colon and you actually do that with the other key:

`ecdsa-koblitz-pubkey:comunicaciones@xertify.co`

**Comment by dalesupa22** [comment]
Thanks for your answer and your help appreciate it 🙏🙏🙏
The point is that it was working before the update without the colon that is strange. 
Adding the column again implies reissue the credentials but it will be fine for us, the most important thing was that we were able to find a solution.

About the other point, you are alright I dont know why we missed the other colon... We will make sure doesnt happen again.

**Comment by lemoustachiste** [comment]
> The point is that it was working before the update without the colon that is strange.

We moved from jsonld@5 to jsonld@8 and this version introduced a safe mode that checks this sort of errors. This is the value that normalization is yielding without the colon on a jsonld playground (https://fhircat.org/jsonld/playground/):

`<https://w3id.org/security#publicKey> <https://fhircat.org/jsonld/playground/ecdsa-koblitz-pubkey0x7B2E3cf80C7C9ECf878427e42059A6a306AEF244> .`

And this is the normalized version with the colon:
`_:c14n5 <https://w3id.org/security#publicKey> <ecdsa-koblitz-pubkey:0x7B2E3cf80C7C9ECf878427e42059A6a306AEF244> .`

As you can see, in the first case it's using the URL of the testing website, which means it's a relative reference because it does not know how to bind it correctly.

I'm by no means a jsonld expert so I can't tell you more about the internals, but I've had to debug such issues before.

**Comment by dalesupa22** [comment]
Thank you so much for the additional information bro Im going to close the issue for now... By the way I invite you to follow me https://twitter.com/dannysuarez . All the best!!!!!
