### ISSUE TITLE
unable to use cert-verifier-js package

### ISSUE THREAD

**Issue by HamzaBinSarfraz** [blockchain-certificates/cert-verifier-js#214]
**Describe the bug**

i installed cert-verifier-js as npm package then i  require the package 

**var Certificate = require('@blockcerts/cert-verifier-js');**

and trying to Verify a Blockcert certificate

but i am keep getting error

**TypeError: global$1.XMLHttpRequest is not a constructor**

in am running node v10.16.0 and npm 6.9.0

here is code snippet which i try to run 

```
const Certificate = require('@blockcerts/cert-verifier-js');

const fs = require('fs');

fs.readFile('./certificate.json', 'utf8', function (err, data) {
    if (err) {
        console.log(err);
    }

    let certificate = new Certificate(data);
    const verificationResult = await certificate.verify(({ code, label, status, errorMessage }) => {
        console.log('Code:', code, label, ' - Status:', status);
        if (errorMessage) {
            console.log(`The step ${code} fails with the error: ${errorMessage}`);
        }
    });

    if (verificationResult.status === 'failure') {
        console.log(`The certificate is not valid. Error: ${verificationResult.errorMessage}`);
    }
});
```
Getting this error

./node_modules/@blockcerts/cert-verifier-js/dist/verifier.js:1
"use strict";function startsWith(e,t){return"string"!=typeof e?(console.warn("Trying to test a non string variable"),!1):0===e.indexOf(t)}Object.defineProperty(exports,"__esModule",{value:!0});const blockCypherUrl="https://api.blockcypher.com/v1/btc/main/txs/",blockCypherTestUrl="https://api.blockcypher.com/v1/btc/test3/txs/",chainSoUrl="https://chain.so/api/v2/get_tx/BTC/",chainSoTestUrl="https://chain.so/api/v2/get_tx/BTCTEST/",etherScanMainUrl="https://api.etherscan.io/api?module=proxy",etherScanRopstenUrl="https://api-ropsten.etherscan.io/api?module=proxy";var API_URLS={blockCypherUrl:blockCypherUrl,blockCypherTestUrl:blockCypherTestUrl,chainSoUrl:chainSoUrl,chainSoTestUrl:chainSoTestUrl,etherScanMainUrl:etherScanMainUrl,etherScanRopstenUrl:etherScanRopstenUrl};const V1_1="1.1",V1_2="1.2",V2_0="2.0";var CERTIFICATE_VERSIONS={V1_1:V1_1,V1_2:V1_2,V2_0:V2_0};const formatValidation="formatValidation",hashComparison="h

TypeError: global$1.XMLHttpRequest is not a constructor
    at checkTypeSupport (/node_modules/@blockcerts/cert-verifier-js/dist/verifier.js:1:89756)
    at Object.<anonymous> (/node_modules/@blockcerts/cert-verifier-js/dist/verifier.js:1:90080)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/server.js:53:21)

**Comment by lemoustachiste** [comment]
So XMLHttpRequest is not natively supported by nodejs, which I think is your use case. As per the solution for your specific use case I am not entirely certain.

You could try using a polyfill and assigning it to `global$1.XMLHttpRequest` manually. It's dirty, so that's fine if you just want to test out, but I'm not sure if that would necessarily work.

 If you are looking at something more stable, you could try to create a new wrapper (read package) around `cert-verifier-js` with Webpack and Rollup, and include `XMLHttpRequest` in it.

Last option I can think of is outputting a `cert-verifier-js` version just for node, but I don't think we can work on that at this moment (but you can propose something).

Eventually it really all boils down to what you are trying to achieve. Do you want a server side script to verify batches of certificates? At this point `cert-verifier-js` is not capable of this (unless one of the above is done).
Do you want a node endpoint to verify certificates? It might be redundant as you would need a client side script to interrogate that endpoint, which essentially is what `cert-verifier-js` does already (interrogating verification endpoints).

If it's just for trying out, I would suggest you use the browser instead.

You can also take a look at https://github.com/blockchain-certificates/blockcerts-verifier which renders and verifies specific certificates (but no automation offered).

**Comment by HamzaBinSarfraz** [comment]
This is helpfull, thanks

**Comment by lemoustachiste** [comment]
you can now use the code exposed in the `lib` folder of the package. This one runs on nodejs.
