### ISSUE TITLE
Verifier can't load external context

### ISSUE THREAD

**Issue by unlimit** [blockchain-certificates/cert-verifier-js#29]
If certificate has an external context(that is not preloaded by default), verifier.js throws following error:
`TypeError: request is not a function
    at loadDocument (./cert-verifier-js/verifier.js:21623:5)
    at jsonld.RequestQueue._loader (./cert-verifier-js/verifier.js:21598:5)
    at jsonld.RequestQueue.add (./cert-verifier-js/verifier.js:21382:10)
`

**Comment by guix77** [comment]
Same

**Comment by lemoustachiste** [comment]
Could you provide more info:
- an example of the certificate you use
- an example of the code you use to get to this problem

Thanks

**Comment by guix77** [comment]
Hi,

A certificate example : https://raw.githubusercontent.com/guix77/blockcerts-certificates/master/certificates/ropsten/talao/test4.json

It should load the external context https://raw.githubusercontent.com/guix77/blockcerts-certificates/master/schema/1.0-alpha1/context.json

The code is here : https://github.com/guix77/react-blockcerts/blob/master/src/Blockcerts.js

It works very well without any external context, basically it's:

```
import { Certificate, CertificateVerifier } from 'cert-verifier-js';
verifyCertificate() {
    if (this.state.certificateJson) {
      let verifier = new CertificateVerifier(
        JSON.stringify(this.state.certificateJson),
        this.verifierStepper
      );
      verifier
      .verify()
      .then(result => this.setState({verifierResult: result}))
      .catch(e => console.error(e));
    }
}
```

**Comment by guix77** [comment]
Just for reference, when I inject the additional definitions in the context directly, it works : https://raw.githubusercontent.com/guix77/blockcerts-certificates/master/certificates/ropsten/talao/test6.json verifies in my React component and on BlockCerts.org web component

**Comment by lemoustachiste** [comment]
@guix77 that's how we handle it too, and I would recommend you take that approach for the time being. I'll dig a bit further on that bug.

**Comment by guix77** [comment]
OK merci Julien, je reste sur cette lancée alors :)

**Comment by lemoustachiste** [comment]
ok I have found the bug.

The version of `jsonld` used in the `cert-verifier-js` is pretty old (0.4.12) when new version is 1.0.2. I initially tried just upgrading the version, hoping naively this would fix the problem, but then I have build errors (both on master and v2-wip branches).

So I dug a bit more and understood the problem.

Here: https://github.com/blockchain-certificates/cert-verifier-js/blob/master/lib/checks.js#L138 we are defining our own `customLoader` if the context is not defined in a supported list (the external contexts).

This custom loader is `jsonld.documentLoaders.node`, which returns a function that indeed takes 2 parameters, the `url` and the `callback`. 

This is an excerpt of the function:

```jsonld.documentLoaders.node = function(options) {
  options = options || {};
  var strictSSL = ('strictSSL' in options) ? options.strictSSL : true;
  var maxRedirects = ('maxRedirects' in options) ? options.maxRedirects : -1;
  var request = ('request' in options) ? options.request : ignore; << Problem is here
  var acceptHeader = 'application/ld+json, application/json';
  var http = ignore;
```
 As marked, the problem is above, when defining the `request` object. 

In the actual code of jsonld, this line is as follows:
`var request = ('request' in options) ? options.request : require('request');`

But the transpiled version, for the browser I assume, drops the `require` and replaces the function by an empty object.

Which when we call in the `loadDocument` function (which is what was returned by the instantiation), fails with above error on that instruction:

```request({
      url: url,
      headers: headers,
      strictSSL: strictSSL,
      followRedirect: false
    }, handleResponse);```

Since, indeed, it is not a function, but rather an empty object.

So the solution to this bug is when instantiating the `customLoader`, pass in a function that can handle the request.

`var customLoader = jsonld.documentLoaders.node({ request: request })`

That `request` function should take in 2 parameters, an `option` and a `callback` which would be called with the following API: `handleResponse(err, res, body)` (since handleResponse is what is being passed to the `request` callback).

I'm guessing that our own `request` could just be a wrapper for a `fetch` (no IE11 support though) or a more classic `xmlHttpRequest`. 

Now I have other priorities to tend to, so I can't dedicate time just now to that, but PRs are welcome.

Otherwise, as mentioned above, you can use the workaround of directly assigning your context items to the `@context` key of your certificate definition, rather than trying to retrieve an external URL.

**Comment by guix77** [comment]
Wow thanks a lot for this complete research :)

I'll probably stick to the embedded items for now and might have a look a it later.

Thanks again!

**Comment by lemoustachiste** [comment]
More work arose on this recently and I think this should not be an error anymore.
We are now using the `xhr` documentLoader in the browser, and the `node` one in nodejs, which was, essentially, the issue here (I ran into it in the past couple of weeks).

**Comment by guix77** [comment]
@lemoustachiste Thanks Julien. ATM I'm not using this feature any more and can not totally confirm for now. However I had the exact same problem `xhr` VS `node` on another related project so I'm confirming at 99% :)
